"""empty message

Revision ID: 41d9192b348b
Revises: 4991c6c09946
Create Date: 2019-08-18 22:38:45.024575

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '41d9192b348b'
down_revision = '4991c6c09946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('text', sa.String(length=140), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_id'],
                        ['user.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet')
    # ### end Alembic commands ###
